name: Build and Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install libgbm-dev

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/checkout@v4
      with:
        ref: content
        path: content

    - name: Install
      run: npm install

    - name: Test
      run: npm run test
