name: Build and Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

    # This is needed by puppeteer
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install libgbm-dev

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v2
      with:
        hugo-version: '0.80.0'

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        submodules: true

    - name: Install
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test