name: Publish Theme
on:
  workflow_dispatch:
  push:
    branches:
      - v2
jobs:
  publish-theme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy theme to tmp
        run: |
          mkdir -p /tmp/hugo-styleguide-theme
          cp -r assets layouts static theme.toml LICENSE README.md /tmp/hugo-styleguide-theme/
      - name: Prep Release
        run: |
          git config --global user.name 'Matt Gaunt'
          git config --global user.email 'hello@gaunt.dev'
          git checkout -B release-theme origin/release-theme
          git rm -rfq .
          git clean -fdxq
          cp -r /tmp/hugo-styleguide-theme/. ./
      - name: Commit theme
        run: |
          git add -A
          git diff --cached --quiet || git commit -m "Automated release"
          git push origin release-theme
